`ifndef CNN_QUANT_PARAMS_VH
`define CNN_QUANT_PARAMS_VH

// Generated by scripts/cnn_lwdd_bitexact.py.
// Input pixels are lower 8 bits, stored as unsigned int16 0..255.
`define CNN_INPUT_FRAC_BITS 8
`define CNN_DENSE_BIAS_SHIFT 11
`define CNN_CONV1_SHIFT 15 // scale=2.7946278097704709e-05, nearest_pow2_shift=15
`define CNN_CONV2_SHIFT 16 // scale=1.9332871218932887e-05, nearest_pow2_shift=16
`define CNN_CONV3_SHIFT 16 // scale=1.9820186075854425e-05, nearest_pow2_shift=16
`define CNN_CONV4_SHIFT 16 // scale=2.1108615590134316e-05, nearest_pow2_shift=16
`define CNN_CONV5_SHIFT 16 // scale=1.9927222316824717e-05, nearest_pow2_shift=16
`define CNN_CONV6_SHIFT 16 // scale=1.607812691183076e-05, nearest_pow2_shift=16

`endif
